# Generated by Django 2.0.6 on 2019-02-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0002_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
